server:
  servlet:
    port: 8080


spring:

  application:
    name: tracker-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tracker
    username:
    password:

  jpa:
    properties:
      hibernate:
        temp:use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true



